---
abstract: 'Create PDF slide from images'
author:
  - 'Daisuke Murase <typester@cpan.org>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.73'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: PDF-FromImage
no_index:
  directory:
    - inc
    - t
requires:
  Imager: 0
  Moose: 0
  PDF::API2: 0
  perl: 5.8.1
version: 0.000002
